version: '3.4'

services:
  camagru:
    image: camagru
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
    environment:
      - CHOKIDAR_USEPOLLING=true
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data:
  
